//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimientos
    {
        public int Id_Movimiento { get; set; }
        public Nullable<int> Id_Departamento { get; set; }
        public Nullable<int> Id_Compra { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<int> Tesorero_Proceso { get; set; }
    
        public virtual Compras Compras { get; set; }
        public virtual Departamento Departamento { get; set; }
    }
}
