//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenesCompra
    {
        public int Id_Orden { get; set; }
        public Nullable<int> Id_Solicitud { get; set; }
        public Nullable<int> Id_Proveedor { get; set; }
        public System.DateTime Fecha_OrdenCompra { get; set; }
    
        public virtual Proveedores Proveedores { get; set; }
        public virtual Solicitudes Solicitudes { get; set; }
    }
}
